\encoding UTF8

\set ON_ERROR_STOP on

-- manual for insights

\copy ztmpclientmigration.insights_portfolio_unlinked_defect_projects from 'insights.portfolio_unlinked_defect_projects.dat'

-- generated  for insights
/*
select format('\copy ztmpclientmigration.insights_%s from ''insights.%s.dat''',table_name,table_name)
from (
    select table_name from information_schema.tables t where
    table_schema='insights'
    and table_type = 'BASE TABLE'
    and table_name not like 'project_module%'
    and table_name not in ('client_user_info','preferences','user_banners','saved_report')
    and table_name not like 'test_cycle%'
    and exists (    select 1 from information_schema.columns
                    where table_schema='insights'
                    and column_name = 'clientid'
                    and table_name = t.table_name)) t
order by table_name asc;
*/
\copy ztmpclientmigration.insights_client_colors from 'insights.client_colors.dat'
\copy ztmpclientmigration.insights_client_landing_page from 'insights.client_landing_page.dat'
\copy ztmpclientmigration.insights_client_user_landing_page from 'insights.client_user_landing_page.dat'
\copy ztmpclientmigration.insights_defect_severities from 'insights.defect_severities.dat'
\copy ztmpclientmigration.insights_defect_severities_detail from 'insights.defect_severities_detail.dat'
\copy ztmpclientmigration.insights_defect_statuses from 'insights.defect_statuses.dat'
\copy ztmpclientmigration.insights_defect_statuses_detail from 'insights.defect_statuses_detail.dat'
\copy ztmpclientmigration.insights_portfolios from 'insights.portfolios.dat'
\copy ztmpclientmigration.insights_portfolio_thresholds from 'insights.portfolio_thresholds.dat'
\copy ztmpclientmigration.insights_portfolio_unlinked_defects from 'insights.portfolio_unlinked_defects.dat'
\copy ztmpclientmigration.insights_rapiddashboardtasks from 'insights.rapiddashboardtasks.dat'
\copy ztmpclientmigration.insights_report_lookup_t from 'insights.report_lookup_t.dat'
\copy ztmpclientmigration.insights_report_lookup_updates from 'insights.report_lookup_updates.dat'
\copy ztmpclientmigration.insights_schedule_tasks from 'insights.schedule_tasks.dat'
\copy ztmpclientmigration.insights_jira_report_fields from 'insights.jira_report_fields.dat'


\copy ztmpclientmigration.clients from 'clients.dat'
\copy ztmpclientmigration.clients_aud from 'clients_aud.dat'
\copy ztmpclientmigration.client_ext from 'client_ext.dat'
\copy ztmpclientmigration.client_licenses from 'client_licenses.dat'
\copy ztmpclientmigration.external_auth_system_config from 'external_auth_system_config.dat'
\copy ztmpclientmigration.client_settings from 'client_settings.dat'
\copy ztmpclientmigration.group_authorities from 'group_authorities.dat'
\copy ztmpclientmigration.configuration_sets from 'configuration_sets.dat'
\copy ztmpclientmigration.configuration_variables from 'configuration_variables.dat'
\copy ztmpclientmigration.audit_log from 'audit_log.dat'
\copy ztmpclientmigration.blob_handles from 'blob_handles.dat'
\copy ztmpclientmigration.blob_handles_aud from 'blob_handles_aud.dat'
\copy ztmpclientmigration.revision_info from 'revision_info.dat'
\copy ztmpclientmigration.revision_aware from 'revision_aware.dat'
\copy ztmpclientmigration.recycle_actions from 'recycle_actions.dat'
\copy ztmpclientmigration.object_assignments from 'object_assignments.dat'
\copy ztmpclientmigration.object_assignments_aud from 'object_assignments_aud.dat'
\copy ztmpclientmigration.queue_event from 'queue_event.dat'
\copy ztmpclientmigration.queue_processing_state from 'queue_processing_state.dat'
\copy ztmpclientmigration.client_users from 'client_users.dat'
\copy ztmpclientmigration.external_client_user from 'external_client_user.dat'
\copy ztmpclientmigration.group_members from 'group_members.dat'
\copy ztmpclientmigration.oauth_authentications from 'oauth_authentications.dat'
\copy ztmpclientmigration.security_profiles from 'security_profiles.dat'
\copy ztmpclientmigration.client_user_sec_profiles from 'client_user_sec_profiles.dat'
\copy ztmpclientmigration.groups from 'groups.dat'
\copy ztmpclientmigration.user_projects from 'user_projects.dat'
\copy ztmpclientmigration.user_criteria from 'user_criteria.dat'
\copy ztmpclientmigration.automation_agents from 'automation_agents.dat'
\copy ztmpclientmigration.automation_hosts from 'automation_hosts.dat'
\copy ztmpclientmigration.automation_status_mapping from 'automation_status_mapping.dat'
\copy ztmpclientmigration.automation_upgrade_logs from 'automation_upgrade_logs.dat'
\copy ztmpclientmigration.automation_cancelled_executions from 'automation_cancelled_executions.dat'
\copy ztmpclientmigration.automation_schedules from 'automation_schedules.dat'
\copy ztmpclientmigration.automation_execution_results from 'automation_execution_results.dat'
\copy ztmpclientmigration.automation_schedule_execution_maps from 'automation_schedule_execution_maps.dat'

\copy ztmpclientmigration.license_blob_handles from 'license_blob_handles.dat'
\copy ztmpclientmigration.custom_field_templates from 'custom_field_templates.dat'
\copy ztmpclientmigration.projects from 'projects.dat'
\copy ztmpclientmigration.projects_aud from 'projects_aud.dat'
\copy ztmpclientmigration.project_key_values from 'project_key_values.dat'
\copy ztmpclientmigration.project_settings from 'project_settings.dat'
\copy ztmpclientmigration.project_default_permissions from 'project_default_permissions.dat'
\copy ztmpclientmigration.project_modules from 'project_modules.dat'
\copy ztmpclientmigration.project_modules_aud from 'project_modules_aud.dat'
\copy ztmpclientmigration.lookup from 'lookup.dat'
\copy ztmpclientmigration.test_beds from 'test_beds.dat'
\copy ztmpclientmigration.custom_fields_aud from 'custom_fields_aud.dat'
\copy ztmpclientmigration.custom_field_configurations_aud from 'custom_field_configurations_aud.dat'
\copy ztmpclientmigration.custom_field_values_aud from 'custom_field_values_aud.dat'
\copy ztmpclientmigration.custom_field_validators from 'custom_field_validators.dat'
\copy ztmpclientmigration.custom_fields from 'custom_fields.dat'
\copy ztmpclientmigration.custom_field_integration_values from 'custom_field_integration_values.dat'
\copy ztmpclientmigration.custom_field_integration_values_aud from 'custom_field_integration_values_aud.dat'
\copy ztmpclientmigration.integration_custom_field_configurations from 'integration_custom_field_configurations.dat'
\copy ztmpclientmigration.integration_custom_field_configurations_aud from 'integration_custom_field_configurations_aud.dat'
\copy ztmpclientmigration.integration_custom_field_data_types from 'integration_custom_field_data_types.dat'
\copy ztmpclientmigration.integration_custom_fields from 'integration_custom_fields.dat'
\copy ztmpclientmigration.integration_custom_fields_aud from 'integration_custom_fields_aud.dat'
\copy ztmpclientmigration.custom_field_template_field_mapping from 'custom_field_template_field_mapping.dat'
\copy ztmpclientmigration.custom_field_data_types from 'custom_field_data_types.dat'
\copy ztmpclientmigration.data_queries from 'data_queries.dat'
\copy ztmpclientmigration.data_query_operators from 'data_query_operators.dat'
\copy ztmpclientmigration.data_query_conditions from 'data_query_conditions.dat'
\copy ztmpclientmigration.client_jira_connection from 'client_jira_connection.dat'
\copy ztmpclientmigration.defect_tracking_connection from 'defect_tracking_connection.dat'
\copy ztmpclientmigration.defect_tracking_connection_test from 'defect_tracking_connection_test.dat'
\copy ztmpclientmigration.defect_tracking_usage from 'defect_tracking_usage.dat'
\copy ztmpclientmigration.defect_tracking_type from 'defect_tracking_type.dat'
\copy ztmpclientmigration.defect_tracking_field from 'defect_tracking_field.dat'

\copy ztmpclientmigration.defect_tracking_project from 'defect_tracking_project.dat'
\copy ztmpclientmigration.integration_external_defect_issue_data from 'integration_external_defect_issue_data.dat'
\copy ztmpclientmigration.integration_defect_issue_data from 'integration_defect_issue_data.dat'
\copy ztmpclientmigration.integration_issue_release_maps from 'integration_issue_release_maps.dat'
\copy ztmpclientmigration.integration_issue_test_case_maps from 'integration_issue_test_case_maps.dat'
\copy ztmpclientmigration.integration_issue_requirement_maps from 'integration_issue_requirement_maps.dat'
\copy ztmpclientmigration.integration_issue_data from 'integration_issue_data.dat'
\copy ztmpclientmigration.integration_external_issues_maps from 'integration_external_issues_maps.dat'
\copy ztmpclientmigration.integration_webhooks from 'integration_webhooks.dat'
\copy ztmpclientmigration.configuration_migration_tracking from 'configuration_migration_tracking.dat'
\copy ztmpclientmigration.integration_external_issues from 'integration_external_issues.dat'
\copy ztmpclientmigration.integration_sync_requirement_tracker from 'integration_sync_requirement_tracker.dat'
\copy ztmpclientmigration.integration_issue_test_case_run_maps from 'integration_issue_test_case_run_maps.dat'
\copy ztmpclientmigration.test_parameters from 'test_parameters.dat'
\copy ztmpclientmigration.test_step_parameter_values from 'test_step_parameter_values.dat'
\copy ztmpclientmigration.test_step_parameters from 'test_step_parameters.dat'
\copy ztmpclientmigration.test_step_parameters_aud from 'test_step_parameters_aud.dat'
\copy ztmpclientmigration.requirements from 'requirements.dat'
\copy ztmpclientmigration.requirements_aud from 'requirements_aud.dat'
\copy ztmpclientmigration.builds from 'builds.dat'
\copy ztmpclientmigration.builds_aud from 'builds_aud.dat'
\copy ztmpclientmigration.releases from 'releases.dat'
\copy ztmpclientmigration.releases_aud from 'releases_aud.dat'
\copy ztmpclientmigration.test_cases from 'test_cases.dat'
\copy ztmpclientmigration.test_cases_aud from 'test_cases_aud.dat'

\copy ztmpclientmigration.requirement_test_cases from 'requirement_test_cases.dat'
\copy ztmpclientmigration.test_case_run from 'test_case_run.dat'
\copy ztmpclientmigration.test_case_run_aud from 'test_case_run_aud.dat'
\copy ztmpclientmigration.test_case_versions from 'test_case_versions.dat'
--\copy ztmpclientmigration.test_case_versions_aud from 'test_case_versions_aud.dat'
\copy ztmpclientmigration.test_case_versions_aud from program 'cmd /c "type test_case_versions_aud.dat"'
\copy ztmpclientmigration.test_cycles from 'test_cycles.dat'
\copy ztmpclientmigration.test_cycles_aud from 'test_cycles_aud.dat'

\copy ztmpclientmigration.test_data_sets from 'test_data_sets.dat'
\copy ztmpclientmigration.test_suites from 'test_suites.dat'
\copy ztmpclientmigration.test_suites_aud from 'test_suites_aud.dat'
--\copy ztmpclientmigration.test_steps from 'test_steps.dat'
\copy ztmpclientmigration.test_steps from program 'cmd /c "type test_steps.dat"'
--\copy ztmpclientmigration.test_steps_aud from 'test_steps_aud.dat'
\copy ztmpclientmigration.test_steps_aud from program 'cmd /c "type test_steps_aud.dat"'
\copy ztmpclientmigration.test_steps_test_cases_aud from 'test_steps_test_cases_aud.dat'
\copy ztmpclientmigration.test_step_results from 'test_step_results.dat'
\copy ztmpclientmigration.test_step_results_aud from 'test_step_results_aud.dat'

\copy ztmpclientmigration.test_case_results from 'test_case_results.dat'
\copy ztmpclientmigration.test_case_results_aud from 'test_case_results_aud.dat'
\copy ztmpclientmigration.defects from 'defects.dat'
\copy ztmpclientmigration.defects_aud from 'defects_aud.dat'
\copy ztmpclientmigration.test_case_result_defects from 'test_case_result_defects.dat'
\copy ztmpclientmigration.test_step_result_defects from 'test_step_result_defects.dat'
\copy ztmpclientmigration.requirement_link_data from 'requirement_link_data.dat'
\copy ztmpclientmigration.requirement_link_data_aud from 'requirement_link_data_aud.dat'
\copy ztmpclientmigration.defect_workflow_transition from 'defect_workflow_transition.dat'
\copy ztmpclientmigration.defect_workflow_transition_profile from 'defect_workflow_transition_profile.dat'
\copy ztmpclientmigration.defect_workflow_transition_status from 'defect_workflow_transition_status.dat'
\copy ztmpclientmigration.object_links from 'object_links.dat'
\copy ztmpclientmigration.incidents from 'incidents.dat'
\copy ztmpclientmigration.scenario_status_mapping from 'scenario_status_mapping.dat'
\copy ztmpclientmigration.combined_parameter_values from 'combined_parameter_values.dat'
\copy ztmpclientmigration.browser_hit_track from 'browser_hit_track.dat'
\copy ztmpclientmigration.request_execution_time from 'request_execution_time.dat'
\copy ztmpclientmigration.object_comments from 'object_comments.dat'
\copy ztmpclientmigration.object_comments_aud from 'object_comments_aud.dat'
\copy ztmpclientmigration.app_url_config from 'app_url_config.dat'
\copy ztmpclientmigration.user_unique_id from 'user_unique_id.dat'
\copy ztmpclientmigration.object_subscribers from 'object_subscribers.dat'
\copy ztmpclientmigration.launch_user_setting from 'launch_user_setting.dat'
\copy ztmpclientmigration.ldap_configuration from 'ldap_configuration.dat'
\copy ztmpclientmigration.insights_token from 'insights_token.dat'
\copy ztmpclientmigration.data_grid_views from 'data_grid_views.dat'
\copy ztmpclientmigration.data_grid_view_fields from 'data_grid_view_fields.dat'
\copy ztmpclientmigration.test_case_agents from 'test_case_agents.dat'
\copy ztmpclientmigration.defect_queries from 'defect_queries.dat'

\copy ztmpclientmigration.reports from 'reports.dat'
\copy ztmpclientmigration.client_user_settings from 'client_user_settings.dat'
\copy ztmpclientmigration.report_settings from 'report_settings.dat'
\copy ztmpclientmigration.defect_query_clauses from 'defect_query_clauses.dat'
\copy ztmpclientmigration.task_execution_time from 'task_execution_time.dat'
\copy ztmpclientmigration.sso_idp_metadata_file from 'sso_idp_metadata_file.dat'
\copy ztmpclientmigration.tutorial_task_users from 'tutorial_task_users.dat'
\copy ztmpclientmigration.recipient_types from 'recipient_types.dat'
\copy ztmpclientmigration.object_tags from 'object_tags.dat'
\copy ztmpclientmigration.lookup_types from 'lookup_types.dat'
\copy ztmpclientmigration.users from 'users.dat'
\copy ztmpclientmigration.configurations from 'configurations.dat'
\copy ztmpclientmigration.integration_projects from 'integration_projects.dat'
\copy ztmpclientmigration.integration_identifier_fields from 'integration_identifier_fields.dat'
\copy ztmpclientmigration.integration_type_maps from 'integration_type_maps.dat'
\copy ztmpclientmigration.integration_defect_fields from 'integration_defect_fields.dat'
\copy ztmpclientmigration.integration_module_fields from 'integration_module_fields.dat'
\copy ztmpclientmigration.integration_release_configuration from 'integration_release_configuration.dat'
\copy ztmpclientmigration.integration_defect_field_maps from 'integration_defect_field_maps.dat'
\copy ztmpclientmigration.integration_release_data from 'integration_release_data.dat'
\copy ztmpclientmigration.integration_requirement_field_maps from 'integration_requirement_field_maps.dat'
--\copy ztmpclientmigration.custom_field_values from 'custom_field_values.dat'
\copy ztmpclientmigration.custom_field_values from program 'cmd /c "type custom_field_values.dat"'
\copy ztmpclientmigration.custom_field_configurations from 'custom_field_configurations.dat'
\copy ztmpclientmigration.user_ext from 'user_ext.dat'
\copy ztmpclientmigration.acl_sid from 'acl_sid.dat'
\copy ztmpclientmigration.acl_object_identity from 'acl_object_identity.dat'
\copy ztmpclientmigration.acl_entry from 'acl_entry.dat'
\copy ztmpclientmigration.automation_parsers from 'automation_parsers.dat'
\copy ztmpclientmigration.client_licenses_aud from 'client_licenses_aud.dat'
\copy ztmpclientmigration.pid_increment from 'pid_increment.dat'
\copy ztmpclientmigration.recycle_related_actions from 'recycle_related_actions.dat'
\copy ztmpclientmigration.user_groups from 'user_groups.dat'
\copy ztmpclientmigration.user_groups_aud from 'user_groups_aud.dat'
\copy ztmpclientmigration.user_group_authorities from 'user_group_authorities.dat'
\copy ztmpclientmigration.user_group_authorities_aud from 'user_group_authorities_aud.dat'
\copy ztmpclientmigration.user_group_members from 'user_group_members.dat'
\copy ztmpclientmigration.user_group_members_aud from 'user_group_members_aud.dat'

\copy ztmpclientmigration.null_revision_info from 'null_revision_info.dat'
